name: orangepi3b kernel
on:
    push:
        branches: ["6.11"]

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set current ref as env variable
              run: |
                echo "GIT_DESC=$(git log -1 --format=%cd.%h --date=format:%Y-%m-%d_%H:%M:%S)" >> $GITHUB_ENV
                ls -al
        
            - name: 构建docker环境
              run: |
                docker version
                docker build -t archlinux_builder:latest .
                
            
            - name: 编译内核
              run: |
                docker run --rm -v $GITHUB_WORKSPACE:/workspace -u user archlinux_builder:latest just build

            - name: Archive artifact
              uses: actions/upload-artifact@v4
              with:
                path: |
                  ./*.tar.zst  